pipeline {
    agent any
	tools{
		go 'Go_1.23.1'
	}
    stages {
        stage('Build') {
            steps {
                sh 'go build -o myapp'
            }
        }
        stage('Run') {
            steps {
                echo 'Running'
            }
        }
    }
}
