pipeline { 
    agent any 
     
    stages { 
        stage('Сборка') { 
            steps { 
                echo 'Выполняем команды для сборки' 
            } 
        } 
        stage('Тестирование') { 
            steps { 
                echo 'Тестируем нашу сборку' 
            } 
        } 
        stage('Развертывание') { 
            steps { 
                echo 'Развертываем все это' 
            } 
        } 
    } 
}
