pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'go build -o myapp'
            }
        }
        stage('Run') {
            steps {
               echo 'RUNNING'
            }
        }
    }
}
